### ISSUE TITLE
Installation and running problems

### ISSUE THREAD

**Issue by jtsoftware** [ThuraAung1601/mmCRFseg#1]
Installation gives an error:

C:\tst\mm-Word-Seg>pip install -r python-crfsuite
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'python-crfsuite'

But still seemed to be installed:

pip install python-crfsuite
Requirement already satisfied: python-crfsuite in c:\users\johnt\appdata\local\programs\python\python310\lib\site-packages (0.9.9)

Running gives error:

C:\tst\mm-Word-Seg>python ./seg.py -i input.txt -o output.txt
Traceback (most recent call last):
  File "C:\tst\mm-Word-Seg\seg.py", line 19, in <module>
    tagger.open('./mm-word-300.crfsuite')
  File "pycrfsuite/_pycrfsuite.pyx", line 571, in pycrfsuite._pycrfsuite.Tagger.open
  File "pycrfsuite/_pycrfsuite.pyx", line 733, in pycrfsuite._pycrfsuite.Tagger._check_model
FileNotFoundError: [Errno 2] No such file or directory: './mm-word-300.crfsuite'

Copying model\mm-word-segmentation-300.crfsuite to .\mm-word-300.crfsuite got rid of the error, but the output is not segmented.

Input:

ເຈົ້າມັກເຮັດຫຍັງເວລາຫວ່າງ?
ເຈົ້າເຮັດຫຍັງເວລາຫວ່າງ?
ໃນເວລາຫວ່າງຂ້ອຍມັກຟັງເພງ
ເຈົ້າມັກເຮັດຫຍັງ?

Output:

ເຈົ້າມັກເຮັດຫຍັງເວລາຫວ່າງ?
ເຈົ້າເຮັດຫຍັງເວລາຫວ່າງ?
ໃນເວລາຫວ່າງຂ້ອຍມັກຟັງເພງ
ເຈົ້າມັກເຮັດຫຍັງ?

**Comment by thuraaungjune** [comment]
Thank you for your review.
I will try to fix it. (Soon there will be updated Myanmar language
processing tool).
The model is only for Myanmar language.

**Comment by jtsoftware** [comment]
So sorry. I got confused about languages.
